### ISSUE TITLE
Can't execute dep db:pull live

### ISSUE THREAD

**Issue by blankse** [sourcebroker/deployer-extended-symfony4#1]
When I want execute `dep db:pull live` I get following error:

```
In db:pull.php line 12:
                                                        
  The target instance is required for db:pull command.
```

**Comment by kszymukowicz** [comment]
Can you try `dev-master` and if this does not help plz give me output of `dep db:pull live -vvv` ?

**Comment by blankse** [comment]
@kszymukowicz It works now with `dev-master`

I have now used the `deployer-extended-database` package.
For the database settings I use the `\SourceBroker\DeployerExtendedDatabase\Driver\EnvDriver`
This use the `DATABASE_HOST`, `DATABASE_NAME`, `DATABASE_USER`, `DATABASE_PASSWORD` envs.

After install of `deployer-extended-symfony4` I must also set the `DATABASE_URL`. Can we make this optional?

**Comment by blankse** [comment]
I opened a PR for this: https://github.com/sourcebroker/deployer-extended-symfony4/pull/2

This issue can be closed.
